# Ultralytics YOLO 🚀, AGPL-3.0 license
# Builds ultralytics/ultralytics:latest images on DockerHub https://hub.docker.com/r/ultralytics

name: Publish Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Select Docker Image
        options:
          - Arm64
          - Jetson
          - Python
          - CPU
          - GPU

jobs:
  docker:
    if: github.repository == 'ultralytics/ultralytics'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg: [
          {dockerfile: "Dockerfile-arm64", platforms: "linux/arm64", tags: "latest-arm64", image: "Arm64"},
          {dockerfile: "Dockerfile-jetson", platforms: "linux/arm64", tags: "latest-jetson", image: "Jetson"},
          {dockerfile: "Dockerfile-python", platforms: "linux/amd64", tags: "latest-python", image: "Python"},
          {dockerfile: "Dockerfile-cpu", platforms: "linux/amd64", tags: "latest-cpu", image: "CPU"},
          {dockerfile: "Dockerfile", platforms: "linux/amd64", tags: "latest", image: "GPU"}
        ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.cfg.platforms }}
          file: docker/${{ matrix.cfg.dockerfile }}
          push: false
          load: true
          tags: ultralytics/ultralytics:${{ matrix.cfg.tags }}

      - name: Run tests
        if: matrix.cfg.image == 'Python'
        run: |
          docker run ultralytics/ultralytics:${{ matrix.cfg.tags }} /bin/bash -c "pip install 'ultralytics[dev]' && pytest tests"

      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.cfg.platforms }}
          file: docker/${{ matrix.cfg.dockerfile }}
          push: false
          tags: ultralytics/ultralytics:${{ matrix.cfg.tags }}
